### ISSUE TITLE
Testing durations

### ISSUE THREAD

**Issue by rigaux** [gregchapman-dev/musicdiff#10]
Hi again

Currently, durations are indirectly tested via beam and note heads. If the OMR does no recognise beams, a duration error will be reported even if durations are correct. This results in many errors that we would like to ignore in some cases.  

On the other hand (and more importantly), if beaming are not used at all in the source image, quavers and quarters for instance will be considered as equivalent (same beaming, same note head), and the duration error will not be reported.

I suggest that musicdiff checks beams and durations independently.

Cheers

Philippe

**Comment by gregchapman-dev** [comment]
Please attach the two files that you diffed, that demonstrates this problem.

**Comment by gregchapman-dev** [comment]
Figured out a bit more here.  A non-beamed flag is annotated during musicdiff as a partial beam (which is "sort of" what it looks like, and represents duration accurately).  So I'm not seeing anything that would cause duration to be treated inaccurately.  I'm definitely going to need some example files that show duration being treated inaccurately.

**Comment by gregchapman-dev** [comment]
Philippe tells me this is no longer a problem.

**Comment by rigaux** [comment]
Hello Greg

Sorry, I have not found the time to check that. Will do asap (next week I guess).

Thanks a lot
P.

**Comment by gregchapman-dev** [comment]
Re-opening until @rigaux has tested to be sure this works properly.

**Comment by rigaux** [comment]
OK, seems to work fine. The issue can be closed as far as I am concerned.
