### ISSUE TITLE
musicdiff fails sometimes - how to contribute?

### ISSUE THREAD

**Issue by rigaux** [gregchapman-dev/musicdiff#8]
Hi there, and thanks for the great tool ! I happen to  be the former advisor of Francesco, and it turns out that I do need to apply musicdiff to an OMR project.

Already installed, and it works well in general. I found however some situations where the diff function breaks (for instance when attempting to manipulate pitches on Rest objects). So either I branch or fork the project to contribute, or report issues with examples. 

Not sure this is the right place to ask this question, but now it's done :-) Waiting for your recommendations.

Philippe

**Comment by gregchapman-dev** [comment]
Hi!  Definitely write an issue, and feel free to fork and contribute PRs.

**Comment by gregchapman-dev** [comment]
When writing up any issue, please include the detail level you are using (or if you are leaving it at the default level).

**Comment by gregchapman-dev** [comment]
Also, feel free to contact me directly at gregc at mac dot com.

**Comment by gregchapman-dev** [comment]
Closing this issue, since it was just a question.  We're off and running now...
